version: "3.9"

# Services
#  - pgadmin: PostgreSQL Admin
#  - frontend: Production frontend
#  - backend: Production backend

services:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 8080
    volumes:
     - pgadmin_data:/var/lib/pgadmin
    network_mode: host

volumes:
  pgadmin_data: {}
